/*
SQLyog Ultimate v11.22 (32 bit)
MySQL - 5.1.51-community : Database - cdsidb_new
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`cdsidb_new` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `cdsidb_new`;

/*Table structure for table `si_local_trade_record` */

DROP TABLE IF EXISTS `si_local_trade_record`;

CREATE TABLE `si_local_trade_record` (
  `ID` int(11) NOT NULL AUTO_INCREMENT COMMENT '唯一标识',
  `ACCOUNTSTREAMCODE` varchar(30) DEFAULT NULL COMMENT '记账流水号',
  `BATCHNUMBER` varchar(50) DEFAULT NULL COMMENT '批次编号',
  `CENTERCODE` varchar(10) DEFAULT NULL,
  `PERSONCODE` varchar(20) DEFAULT NULL COMMENT '个人编码',
  `SICODE` varchar(10) DEFAULT NULL COMMENT '社保编码',
  `COSTCODE` varchar(10) DEFAULT NULL COMMENT '费用编码',
  `FULLNAME` varchar(50) DEFAULT NULL COMMENT '姓名',
  `GENDER` varchar(2) DEFAULT NULL COMMENT '性别',
  `BIRTHDAY` date DEFAULT NULL COMMENT '出生日期',
  `AGE` int(4) DEFAULT NULL COMMENT '年龄',
  `PERSONSTATUS` varchar(10) DEFAULT NULL COMMENT '人员状态',
  `UNITCODE` varchar(20) DEFAULT NULL COMMENT '单位编码',
  `DETAILSCOUNT` int(4) DEFAULT NULL COMMENT '明细条数',
  `COSTTOTAL` decimal(10,4) DEFAULT NULL COMMENT '费用总额',
  `FULLEXPENSEPART` decimal(10,4) DEFAULT NULL COMMENT '全自费部分',
  `SELFPAYPART` decimal(10,4) DEFAULT NULL COMMENT '挂钩自付部分',
  `ACCORDRANGEPART` decimal(10,4) DEFAULT NULL COMMENT '符合范围部分',
  `PERSONPAYTOTAL` decimal(10,4) DEFAULT NULL COMMENT '个人账户支付总额',
  `SIPAYTOTAL` decimal(10,4) DEFAULT NULL COMMENT '社保基金支付总额',
  `ACCOUNTSNUMBER` varchar(30) DEFAULT NULL COMMENT '结算编号',
  `PAYMENTCATEGORY` varchar(10) DEFAULT NULL COMMENT '支付类别',
  `REIMBURSEMENTTYPE` varchar(10) DEFAULT NULL COMMENT '报销类型',
  `OPERATORCODE` varchar(20) DEFAULT NULL COMMENT '经办人编码',
  `OPERATORNAME` varchar(50) DEFAULT NULL COMMENT '经办人姓名',
  `OPERATETIME` datetime DEFAULT NULL COMMENT '经办时间',
  `LIQUIDATIONCENTER` varchar(10) DEFAULT NULL COMMENT '清算分中心',
  `LIQUIDATIONMARK` varchar(10) DEFAULT NULL COMMENT '清算标志',
  `LIQUIDATIONAPPLYSTREAMBILL` varchar(30) DEFAULT NULL COMMENT '清算申请流水单',
  `LINQUIDATIONCATEGORY` varchar(20) DEFAULT NULL COMMENT '清算类别',
  `BACKMARK` varchar(10) DEFAULT NULL COMMENT '回退标志',
  `UNCERTAINRRECORDMARK` varchar(10) DEFAULT NULL COMMENT '不确定记录标志',
  `HANDLESTREMNUMBER` varchar(30) DEFAULT NULL COMMENT '处理流水号',
  `HANDLECHECKCODE` varchar(50) DEFAULT NULL COMMENT '处理验证码',
  `VISITINGPERSON` varchar(50) DEFAULT NULL COMMENT '就诊人员',
  `CARDHOLDERRELATION` varchar(20) DEFAULT NULL COMMENT '持卡人关系',
  `YDFLAG` varchar(10) DEFAULT NULL COMMENT '异地结算标志',
  `REMARKS` varchar(255) DEFAULT NULL COMMENT '备注',
  `SALEORDERNUMBER` varchar(30) DEFAULT NULL COMMENT '销售单号',
  `UPDATETIME` datetime DEFAULT NULL COMMENT '更新时间',
  `UPDATEPERSON` varchar(50) DEFAULT NULL COMMENT '更新人员',
  `CREATETIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CREATEPERSON` varchar(50) DEFAULT NULL COMMENT '创建人员',
  `CREATEPROGRAMID` varchar(20) DEFAULT NULL COMMENT '创建程序ID',
  `CREATEIP` varchar(50) DEFAULT NULL COMMENT '创建IP',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

/*Data for the table `si_local_trade_record` */

insert  into `si_local_trade_record`(`ID`,`ACCOUNTSTREAMCODE`,`BATCHNUMBER`,`CENTERCODE`,`PERSONCODE`,`SICODE`,`COSTCODE`,`FULLNAME`,`GENDER`,`BIRTHDAY`,`AGE`,`PERSONSTATUS`,`UNITCODE`,`DETAILSCOUNT`,`COSTTOTAL`,`FULLEXPENSEPART`,`SELFPAYPART`,`ACCORDRANGEPART`,`PERSONPAYTOTAL`,`SIPAYTOTAL`,`ACCOUNTSNUMBER`,`PAYMENTCATEGORY`,`REIMBURSEMENTTYPE`,`OPERATORCODE`,`OPERATORNAME`,`OPERATETIME`,`LIQUIDATIONCENTER`,`LIQUIDATIONMARK`,`LIQUIDATIONAPPLYSTREAMBILL`,`LINQUIDATIONCATEGORY`,`BACKMARK`,`UNCERTAINRRECORDMARK`,`HANDLESTREMNUMBER`,`HANDLECHECKCODE`,`VISITINGPERSON`,`CARDHOLDERRELATION`,`YDFLAG`,`REMARKS`,`SALEORDERNUMBER`,`UPDATETIME`,`UPDATEPERSON`,`CREATETIME`,`CREATEPERSON`,`CREATEPROGRAMID`,`CREATEIP`) values (1,'00001905154834178','0000S355342326','0000','019503909','892428','01','尹富菊','女','1939-09-12',79,'21','030001',21,'312.3600','0.0000','0.0000','312.3600','312.3600','0.0000','00001905151981105','0201','01','admin','管理员','2019-05-15 15:28:24','0005','0',NULL,NULL,'0',NULL,'11C0000SJ4D8FB731','2430',NULL,'本人',NULL,NULL,'XS201905150001',NULL,NULL,'2019-05-15 15:28:24','管理员','Pay','192.168.1.2'),(3,'00001905319807242','99999999','0000','011367115','416602','01','数据恢复','男','1980-01-01',32,'11','9999999',1,'4500.0000','0.0000','0.0000','4500.0000','4500.0000','0.0000','00001905317873024','0201',NULL,'admin','管理员','2019-05-31 10:46:14','0009','0',NULL,NULL,'0',NULL,'999999999','AAAA',NULL,NULL,NULL,'数据恢复',NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
